### ISSUE TITLE
如何替换小米平板5系列垃圾MagicPointer鼠标指针

### ISSUE THREAD

**Issue by jack007-hub** [Xunflash/SetMiPad5Pointer#2]
替换小米平板5系列垃圾MagicPointer鼠标指针，SetMiPad5Pointer-master.zip这个如何安装，大佬麻烦指教一下，辛苦辛苦

**Comment by Xunflash** [comment]
> 替换小米平板5系列垃圾MagicPointer鼠标指针，SetMiPad5Pointer-master.zip这个如何安装，大佬麻烦指教一下，辛苦辛苦

release页面自行安装apk即可，建议先学学怎么使用github

**Comment by jack007-hub** [comment]
大佬，已经到这一步了，接下来怎么激活，研究了老久还是整不明白，方便的话可以远程一下，感谢感谢！












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xunflash/SetMiPad5Pointer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 凌晨2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xunflash/SetMiPad5Pointer] 如何替换小米平板5系列垃圾MagicPointer鼠标指针 (Issue #2)





  
替换小米平板5系列垃圾MagicPointer鼠标指针，SetMiPad5Pointer-master.zip这个如何安装，大佬麻烦指教一下，辛苦辛苦
  
release页面自行安装apk即可，建议先学学怎么使用github

**Comment by Xunflash** [comment]
> 大佬，已经到这一步了，接下来怎么激活，研究了老久还是整不明白，方便的话可以远程一下，感谢感谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xunflash/SetMiPad5Pointer" ***@***.***&gt;; 发送时间:&nbsp;2022年3月30日(星期三) 凌晨2:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Xunflash/SetMiPad5Pointer] 如何替换小米平板5系列垃圾MagicPointer鼠标指针 (Issue #2) 替换小米平板5系列垃圾MagicPointer鼠标指针，SetMiPad5Pointer-master.zip这个如何安装，大佬麻烦指教一下，辛苦辛苦 release页面自行安装apk即可，建议先学学怎么使用github — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

写的挺清楚了，安装apk之后lsposed勾选系统作用域，如果不会安装lsposed建议去酷安搜索

**Comment by jack007-hub** [comment]
好的，感谢🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 中午1:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xunflash/SetMiPad5Pointer] 如何替换小米平板5系列垃圾MagicPointer鼠标指针 (Issue #2)




  
大佬，已经到这一步了，接下来怎么激活，研究了老久还是整不明白，方便的话可以远程一下，感谢感谢！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xunflash/SetMiPad5Pointer" @.&gt;; 发送时间:&nbsp;2022年3月30日(星期三) 凌晨2:11 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Xunflash/SetMiPad5Pointer] 如何替换小米平板5系列垃圾MagicPointer鼠标指针 (Issue #2) 替换小米平板5系列垃圾MagicPointer鼠标指针，SetMiPad5Pointer-master.zip这个如何安装，大佬麻烦指教一下，辛苦辛苦 release页面自行安装apk即可，建议先学学怎么使用github — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
写的挺清楚了，安装apk之后lsposed勾选系统作用域，如果不会安装lsposed建议去酷安搜索
