### ISSUE TITLE
Add magic pointer for redmi pad

### ISSUE THREAD

**Issue by Ankit2502** [Xunflash/SetMiPad5Pointer#3]
Hi, i really appreciate your work but I just wonder that can you add option to switch cursor to magic pointer on redmi pad as well, as by default in redmipad we get cursor only so it would be really nice if we can switch to magic pointer as it really looks good and gives iPad feel.... Pls...

**Comment by Xunflash** [comment]
Hi, does the Redmi Pad have the default black pointer? Do you mean that you want me to replace the default black pointer with the Magic Pointer of the Mi Pad?

**Comment by Ankit2502** [comment]
yes, it has default black pointer, and i want you to add option to change it to magic pointer like mi pad....

**Comment by Xunflash** [comment]
> yes, it has default black pointer, and i want you to add option to change it to magic pointer like mi pad....

Understood, this may need to hook system framework. I'm not sure if I have time to develop this function...

**Comment by Ankit2502** [comment]
Nevermind we got this feature in MIUI 14 so now no need only issues is now I am not liking it because it is very big in size which make it very hard to read and navigate in the system... You don't even get to see what is exactly below the pointer and what at you are clicking this is big issue when they are copying Mac then they should copy it well, in iPad it is clearly visible on what you clicking at... but here it is very hard the transparency is very low, pointer should be little bit transparent and pointer is thick too... Anyways...
