### ISSUE TITLE
模块与最新版本小米电脑管家互联的共用键盘鼠标不兼容

### ISSUE THREAD

**Issue by yuameshi** [Xunflash/SetMiPad5Pointer#4]
如题：在使用小米电脑管家的控制平板鼠标时，鼠标指针会无法显示（点击屏幕元素有反应），关闭模块后显示为正常magic pointer。

**Comment by yuameshi** [comment]
补充：回退为老版本小米妙想中心没有问题，可能是偶发状况

**Comment by Xunflash** [comment]
> 补充：回退为老版本小米妙想中心没有问题，可能是偶发状况

可以测试一下新版的，之前一直没时间更新这个小项目

**Comment by yuameshi** [comment]
能使
